/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.totematendimentohospital;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author danielle.baer
 */
public class Cadastro extends javax.swing.JFrame {
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        txfNome = new javax.swing.JTextField();
        txfCpf = new javax.swing.JTextField();
        txfIdade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ckbFebre = new javax.swing.JCheckBox();
        ckbDorDeCabeca = new javax.swing.JCheckBox();
        ckbEspirros = new javax.swing.JCheckBox();
        ckbDorDeGarganta = new javax.swing.JCheckBox();
        ckbTosse = new javax.swing.JCheckBox();
        ckbDificuldadeRespiratoria = new javax.swing.JCheckBox();
        ckbDorNoCorpo = new javax.swing.JCheckBox();
        ckbDiarreia = new javax.swing.JCheckBox();
        ckbContatoCovid = new javax.swing.JCheckBox();
        ckbLocalAglomerado = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnMostraLista = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emergência");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ficha para cadastro");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Idade:");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino", "Masculino" }));
        cbSexo.setToolTipText("");

        txfCpf.setToolTipText("");
        txfCpf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txfCpf.setName(""); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Marque abaixo os sintomas que possui:");

        ckbFebre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbFebre.setText("Febre");

        ckbDorDeCabeca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbDorDeCabeca.setText("Dor de cabeça");

        ckbEspirros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbEspirros.setText("Secreção nasal ou espirros");

        ckbDorDeGarganta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbDorDeGarganta.setText("Dor/irritação na garganta");

        ckbTosse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbTosse.setText("Tosse seca");

        ckbDificuldadeRespiratoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbDificuldadeRespiratoria.setText("Dificuldade respiratória");

        ckbDorNoCorpo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbDorNoCorpo.setText("Dores no corpo");

        ckbDiarreia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbDiarreia.setText("Diarréia");

        ckbContatoCovid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbContatoCovid.setText("Nos últimos 14 dias estive em contato com um caso positivo para COVID-19");

        ckbLocalAglomerado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbLocalAglomerado.setText("Estive em locais com grandes aglomerações");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Questionário para análise de risco de contaminação por COVID-19");

        btnSair.setText("Sair");
        btnSair.setToolTipText("");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnMostraLista.setText("Mostrar lista de pacientes");
        btnMostraLista.setToolTipText("");
        btnMostraLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraListaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9)
                        .addGap(8, 8, 8)
                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txfCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ckbDorDeGarganta)
                        .addGap(43, 43, 43)
                        .addComponent(ckbTosse))
                    .addComponent(jLabel6)
                    .addComponent(ckbContatoCovid)
                    .addComponent(ckbLocalAglomerado)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ckbFebre)
                        .addGap(46, 46, 46)
                        .addComponent(ckbDorDeCabeca)
                        .addGap(30, 30, 30)
                        .addComponent(ckbEspirros))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ckbDificuldadeRespiratoria)
                                    .addGap(18, 18, 18)
                                    .addComponent(ckbDorNoCorpo)))
                            .addComponent(btnMostraLista))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbDiarreia))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbContatoCovid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbLocalAglomerado)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbFebre)
                    .addComponent(ckbDorDeCabeca)
                    .addComponent(ckbEspirros))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbDorDeGarganta)
                    .addComponent(ckbTosse))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbDificuldadeRespiratoria)
                    .addComponent(ckbDorNoCorpo)
                    .addComponent(ckbDiarreia))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnMostraLista))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    ArrayList<Paciente> lista = new ArrayList<>();
    Paciente paciente = new Paciente();
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try{
            paciente.Cpf = txfCpf.getText().toUpperCase();
            if(txfCpf.getText().equals("SAIR")){
                System.exit(0);
            }
            paciente.Nome = txfNome.getText();
            paciente.Idade = Integer.parseInt(txfIdade.getText());
            paciente.Sexo = cbSexo.getSelectedItem().toString();
            alasDeRisco();

            lista.add(paciente);
            
            limpaCampos();
            txfCpf.requestFocus(); 
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Por favor, preencha os campos obrigatórios!");
            txfCpf.requestFocus();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed
    
    private void btnMostraListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraListaActionPerformed
        Colecao colecao = new Colecao();
        colecao.recebeLista(lista);
        colecao.setVisible(true);
    }//GEN-LAST:event_btnMostraListaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void limpaCampos(){
        txfCpf.setText("");
        txfNome.setText("");
        txfIdade.setText("");
        cbSexo.setSelectedItem("Selecione");
        ckbContatoCovid.setSelected(false);
        ckbDiarreia.setSelected(false);
        ckbDificuldadeRespiratoria.setSelected(false);
        ckbDorDeCabeca.setSelected(false);
        ckbDorDeGarganta.setSelected(false);
        ckbDorNoCorpo.setSelected(false);
        ckbEspirros.setSelected(false);
        ckbFebre.setSelected(false);
        ckbLocalAglomerado.setSelected(false);
        ckbTosse.setSelected(false);
        
    }
    
    private int verificaCheckComboBox(){
        int cont = 0;
        if(ckbContatoCovid.isSelected()){
            cont = cont + 10;
        }
        if(ckbLocalAglomerado.isSelected()){
            cont = cont + 3;
        }
        if(ckbFebre.isSelected()){
            cont = cont + 5;
        }
        if(ckbDorDeCabeca.isSelected()){
            cont = cont + 1;
        }
        if(ckbEspirros.isSelected()){
            cont = cont + 1;
        }
        if(ckbDorDeGarganta.isSelected()){
            cont = cont + 1;
        }
        if(ckbTosse.isSelected()){
            cont = cont + 3;
        }
        if(ckbDificuldadeRespiratoria.isSelected()){
            cont = cont + 10;
        }
        if(ckbDorNoCorpo.isSelected()){
            cont = cont + 1;
        }
        if(ckbDiarreia.isSelected()){
            cont = cont + 1;
        }  
        return cont;
    }
    
    private void alasDeRisco(){
        int cont = verificaCheckComboBox();
        if(cont < 10){
            JOptionPane.showMessageDialog(null, "Por favor, diriga-se para a ala de risco baixo");
        }else if(cont < 20){
            JOptionPane.showMessageDialog(null, "Por favor, diriga-se para a ala de risco médio");
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, diriga-se para a ala de risco alto");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnMostraLista;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JCheckBox ckbContatoCovid;
    private javax.swing.JCheckBox ckbDiarreia;
    private javax.swing.JCheckBox ckbDificuldadeRespiratoria;
    private javax.swing.JCheckBox ckbDorDeCabeca;
    private javax.swing.JCheckBox ckbDorDeGarganta;
    private javax.swing.JCheckBox ckbDorNoCorpo;
    private javax.swing.JCheckBox ckbEspirros;
    private javax.swing.JCheckBox ckbFebre;
    private javax.swing.JCheckBox ckbLocalAglomerado;
    private javax.swing.JCheckBox ckbTosse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txfCpf;
    private javax.swing.JTextField txfIdade;
    private javax.swing.JTextField txfNome;
    // End of variables declaration//GEN-END:variables
}
